### ISSUE TITLE
Space character on Nodesto Caps Condensed is tiny

### ISSUE THREAD

**Issue by graycastle** [jonathonf/solbera-dnd-fonts#19]
Unsure if this is a known issue or even just a me issue, but on MacOS 12.3.1 the Nodesto Caps Condensed font looks awesome aside from the minuscule space character. Even upping the word spacing to 250% results in titles with virtually no spacing between words.

No issues or warnings when installing the font, all four validate in Font Book (definitely not a font expert here).

**Comment by jonathonf** [comment]
PR is welcome. :wink:

**Comment by graycastle** [comment]
Oh, gotcha! I’ll see what I can do, I’ve never edited a font before. Is FontForge the correct type of tool for the job?

>

**Comment by scottkuhl** [comment]
I believe this is a bug in a newer version of the font.  The version referenced on https://benlk.github.io/solbera-dnd-fonts/#nodesto does not have the issue.

**Comment by will528** [comment]
Yeah @scottkuhl is right. It looks like the bug was introduced in 1.4. If I roll back to 1.3, it has the wrong name (which was fixed in #13), but the space character is correct.

![1_4](https://user-images.githubusercontent.com/23529912/180886879-d9897942-c3c6-48d9-98ee-2cf062b65701.png)
![1_3](https://user-images.githubusercontent.com/23529912/180886883-be540c02-338c-4d7a-9d03-df3700158e06.png)

I'm in the same boat as @graycastle, I've never worked on a font before, but if I diff the fonts in the FontForge tool they mentioned it's just showing the space character width being 20 instead of 508. Is it as simple as changing that value and exporting the font? I'm getting errors about the font being self-intersecting, not sure if that's related or not.

![diff](https://user-images.githubusercontent.com/23529912/180886599-bc129adc-712d-4e6e-ad1c-e2be67070a81.png)

**Comment by lucastucious** [comment]
should be fixed by #21 ... sorry
